### ISSUE TITLE
Macle.idx is not accessible. 

### ISSUE THREAD

**Issue by KarthikStrange** [EvolBioInf/fur#10]
Macle.idx is not accessible. 

i did export bashrc 

export PATH=$PATH:/home/mrstrange/macle

./fur -d /home/mrstrange/SSPD/furDb/
ERROR: Could not open file: /home/mrstrange/SSPD/furDb//macle.idx
open(/home/mrstrange/SSPD/furDb//macle.idx, 0) failed: No such file or directory
error in fur: couldn't run macle -l /home/mrstrange/SSPD/furDb//macle.idx | head -n 6 | tail -n 1 | awk '{print $6 }'

**Comment by haubold** [comment]
It looks as if makeFurDb ended wihout generating the file macle.idx. What happens when you run makeFurDb on your targets and neighbors?

**Comment by KarthikStrange** [comment]
it generated 
 makeFurDb -t /home/mrstrange/SSPD/target/ -n /home/mrstrange/SSPD/neighborhood/ -d furDb
# Reading data...done.
# Making macle index with target representative "/home/mrstrange/SSPD/target/Yellow_fever_complete_nucleotide.fasta"...done.
# Making BLAST database...sh: 1: makeblastdb: not found

i am unable to generate BLAST database.  

Is makeblastdb is a tool macle rely on?

**Comment by KarthikStrange** [comment]
macle.idx got generated but 

# Making BLAST database...sh: 1: makeblastdb: not found

is makeblastdb a seperate tool that macle / fur rely on?

**Comment by haubold** [comment]
Glad to hear that macle.idx was constructed. As to makeblastdb, it is part of the ncbi-blast+ package, which is one of the dependencies of fur. The README of fur should contain the full list of dependencies (and does list ncbi-blast+, I just checked).
