### ISSUE TITLE
fur error

### ISSUE THREAD

**Issue by geronimp** [EvolBioInf/fur#4]
Hi, 

Thanks for developing this software, it looks really useful. I ran into an issue while running simple case of 1 target sequence and 29 neighbors. I noticed this was also reported in issue #2 

After makeFurDb completed without error, I received the following while trying to run fur itself:

```
fur  -d database/
# Step                    Sequences  Nucleotides  Mutations (N)
# -------------------------------------------------------------
# Sliding window               1096       593912              0
error in fur: efopen, can't open database//p.fasta
```

I was able to replicate this issue using a small set of publicly available e coli genomes:
[test.tar.gz](https://github.com/EvolBioInf/fur/files/7614660/test.tar.gz)

Thanks,

Joel

**Comment by haubold** [comment]
Thanks for taking the trouble of pointing this out again and especially for providing an example data set. I've just fixed this bug, so it is now possible to analyze data sets with a single target sequence.

**Comment by geronimp** [comment]
Thanks for the quick response. Seems to work now!
