### ISSUE TITLE
Single target issue still happening in outdated docker version

### ISSUE THREAD

**Issue by priesgo** [EvolBioInf/fur#5]
Thanks for making and sharing fur!

I am running into the issue #4 when trying to use fur for a single target from the docker image. I think the docker image has an older version before #4 was fixed. Would it be possible to update the docker?

**Comment by haubold** [comment]
Thanks for pointing this out, I've just update the docker image.

**Comment by priesgo** [comment]
Thanks for the quick answer! I'll close this issue
