### ISSUE TITLE
PRIMER_MAX_TM error?

### ISSUE THREAD

**Issue by SamMcGreig** [EvolBioInf/fur#7]
Hi,

I think the output of fur2prim is inserting an "f" before PRIMER_MAX_TM. Is this correct or an error?

```
PRIMER_PRODUCT_SIZE_RANGE=70-150
PRIMER_MIN_TM=54.0
fPRIMER_MAX_TM=58.0
PRIMER_INTERNAL_MIN_TM=43.0
PRIMER INTERNAL_MAX_TM=47.0
```

**Comment by haubold** [comment]
Thank you for pointing out that error, I have just fixed it.
